import type { ReactNode } from "react";
import type { ConnectionIconRef } from "../../store/familyTreeStore";
import {
  FaHeart,
  FaStar,
  FaHome,
  FaUser,
  FaUsers,
  FaChild,
  FaBaby,
  FaRing,
  FaCross,
  FaDove,
  FaLeaf,
  FaTree,
  FaSun,
  FaMoon,
  FaCloud,
  FaSnowflake,
  FaFire,
  FaWater,
  FaBolt,
  FaGem,
  FaCrown,
  FaShieldAlt,
  FaKey,
  FaLock,
  FaUnlock,
  FaBook,
  FaGraduationCap,
  FaBriefcase,
  FaPlane,
  FaShip,
  FaCar,
  FaBicycle,
  FaPaw,
  FaCat,
  FaDog,
  FaHorse,
  FaDragon,
  FaGhost,
  FaSkull,
  FaMusic,
  FaPalette,
  FaCamera,
  FaGift,
  FaBell,
  FaFlag,
  FaMapMarkerAlt,
  FaGlobe,
  FaAnchor,
  FaCompass,
  FaEye,
  FaHandPaper,
  FaPrayingHands,
  FaHandshake,
  FaComment,
  FaEnvelope,
  FaPhone,
  FaCalendar,
  FaClock,
  FaHourglass,
  FaInfinity,
  FaPlus,
  FaMinus,
  FaCheck,
  FaTimes,
  FaQuestion,
  FaExclamation,
  FaArrowUp,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
} from "react-icons/fa";
import {
  MdFamilyRestroom,
  MdFavorite,
  MdHome,
  MdPerson,
  MdGroups,
  MdChildCare,
  MdElderly,
  MdWork,
  MdSchool,
  MdLocalHospital,
  MdChurch,
  MdPark,
  MdPets,
  MdSportsSoccer,
  MdMusicNote,
  MdPalette,
  MdCamera,
  MdTravelExplore,
  MdFlight,
  MdDirectionsBoat,
  MdDirectionsCar,
  MdTwoWheeler,
  MdWbSunny,
  MdNightlight,
  MdCloud,
  MdAcUnit,
  MdWhatshot,
  MdWaterDrop,
  MdFlashOn,
  MdDiamond,
  MdEmojiEvents,
  MdSecurity,
  MdVpnKey,
  MdLock,
  MdLockOpen,
  MdMenuBook,
  MdEmail,
  MdPhone,
  MdCalendarToday,
  MdSchedule,
  MdHourglassEmpty,
  MdAllInclusive,
  MdAdd,
  MdRemove,
  MdCheck,
  MdClose,
  MdHelp,
  MdPriorityHigh,
  MdArrowUpward,
  MdArrowDownward,
  MdArrowBack,
  MdArrowForward,
  MdLocationOn,
  MdPublic,
  MdAnchor,
  MdExplore,
  MdVisibility,
  MdPanTool,
  MdVolunteerActivism,
  MdHandshake,
  MdChat,
  MdCardGiftcard,
  MdNotifications,
  MdFlag,
} from "react-icons/md";
import {
  GiFamilyHouse,
  GiLovers,
  GiBabyFace,
  GiCrossMark,
  GiDove,
  GiOakLeaf,
  GiPineTree,
  GiSun,
  GiMoon,
  GiFire,
  GiWaterDrop,
  GiDiamondRing,
  GiCrown,
  GiShield,
  GiKey,
  GiPadlock,
  GiBookCover,
  GiGraduateCap,
  GiBriefcase,
  GiAirplane,
  GiSailboat,
  GiCarKey,
  GiCycle,
  GiPawPrint,
  GiCat,
  GiSittingDog,
  GiHorseHead,
  GiDragonHead,
  GiGhost,
  GiMusicalNotes,
  GiPaintBrush,
  GiPresent,
  GiWorld,
  GiAnchor,
  GiCompass,
  GiHand,
  GiPrayer,
  GiTalk,
  GiEnvelope,
  GiPhone,
  GiCalendar,
  GiSandsOfTime,
  GiInfinity,
  GiCheckMark,
  GiCrossedSwords,
  GiArrowDunk,
  GiLightningBow,
  GiSkullCrossedBones,
} from "react-icons/gi";
import {
  BsHeart,
  BsStar,
  BsHouse,
  BsPerson,
  BsPeople,
  BsEmojiSmile,
  BsSun,
  BsMoon,
  BsCloud,
  BsSnow,
  BsFire,
  BsDroplet,
  BsLightning,
  BsGem,
  BsAward,
  BsShield,
  BsKey,
  BsLock,
  BsUnlock,
  BsBook,
  BsMortarboard,
  BsBriefcase,
  BsAirplane,
  BsWater,
  BsCarFront,
  BsBicycle,
} from "react-icons/bs";

type IconComponent = React.ComponentType<{ size?: number; className?: string }>;

const ICON_MAP: Record<string, IconComponent> = {
  "fa:FaHeart": FaHeart,
  "fa:FaStar": FaStar,
  "fa:FaHome": FaHome,
  "fa:FaUser": FaUser,
  "fa:FaUsers": FaUsers,
  "fa:FaChild": FaChild,
  "fa:FaBaby": FaBaby,
  "fa:FaRing": FaRing,
  "fa:FaCross": FaCross,
  "fa:FaDove": FaDove,
  "fa:FaLeaf": FaLeaf,
  "fa:FaTree": FaTree,
  "fa:FaSun": FaSun,
  "fa:FaMoon": FaMoon,
  "fa:FaCloud": FaCloud,
  "fa:FaSnowflake": FaSnowflake,
  "fa:FaFire": FaFire,
  "fa:FaWater": FaWater,
  "fa:FaBolt": FaBolt,
  "fa:FaGem": FaGem,
  "fa:FaCrown": FaCrown,
  "fa:FaShieldAlt": FaShieldAlt,
  "fa:FaKey": FaKey,
  "fa:FaLock": FaLock,
  "fa:FaUnlock": FaUnlock,
  "fa:FaBook": FaBook,
  "fa:FaGraduationCap": FaGraduationCap,
  "fa:FaBriefcase": FaBriefcase,
  "fa:FaPlane": FaPlane,
  "fa:FaShip": FaShip,
  "fa:FaCar": FaCar,
  "fa:FaBicycle": FaBicycle,
  "fa:FaPaw": FaPaw,
  "fa:FaCat": FaCat,
  "fa:FaDog": FaDog,
  "fa:FaHorse": FaHorse,
  "fa:FaDragon": FaDragon,
  "fa:FaGhost": FaGhost,
  "fa:FaSkull": FaSkull,
  "fa:FaMusic": FaMusic,
  "fa:FaPalette": FaPalette,
  "fa:FaCamera": FaCamera,
  "fa:FaGift": FaGift,
  "fa:FaBell": FaBell,
  "fa:FaFlag": FaFlag,
  "fa:FaMapMarkerAlt": FaMapMarkerAlt,
  "fa:FaGlobe": FaGlobe,
  "fa:FaAnchor": FaAnchor,
  "fa:FaCompass": FaCompass,
  "fa:FaEye": FaEye,
  "fa:FaHandPaper": FaHandPaper,
  "fa:FaPrayingHands": FaPrayingHands,
  "fa:FaHandshake": FaHandshake,
  "fa:FaComment": FaComment,
  "fa:FaEnvelope": FaEnvelope,
  "fa:FaPhone": FaPhone,
  "fa:FaCalendar": FaCalendar,
  "fa:FaClock": FaClock,
  "fa:FaHourglass": FaHourglass,
  "fa:FaInfinity": FaInfinity,
  "fa:FaPlus": FaPlus,
  "fa:FaMinus": FaMinus,
  "fa:FaCheck": FaCheck,
  "fa:FaTimes": FaTimes,
  "fa:FaQuestion": FaQuestion,
  "fa:FaExclamation": FaExclamation,
  "fa:FaArrowUp": FaArrowUp,
  "fa:FaArrowDown": FaArrowDown,
  "fa:FaArrowLeft": FaArrowLeft,
  "fa:FaArrowRight": FaArrowRight,
  "md:MdFamilyRestroom": MdFamilyRestroom,
  "md:MdFavorite": MdFavorite,
  "md:MdHome": MdHome,
  "md:MdPerson": MdPerson,
  "md:MdGroups": MdGroups,
  "md:MdChildCare": MdChildCare,
  "md:MdElderly": MdElderly,
  "md:MdWork": MdWork,
  "md:MdSchool": MdSchool,
  "md:MdLocalHospital": MdLocalHospital,
  "md:MdChurch": MdChurch,
  "md:MdPark": MdPark,
  "md:MdPets": MdPets,
  "md:MdSportsSoccer": MdSportsSoccer,
  "md:MdMusicNote": MdMusicNote,
  "md:MdPalette": MdPalette,
  "md:MdCamera": MdCamera,
  "md:MdTravelExplore": MdTravelExplore,
  "md:MdFlight": MdFlight,
  "md:MdDirectionsBoat": MdDirectionsBoat,
  "md:MdDirectionsCar": MdDirectionsCar,
  "md:MdTwoWheeler": MdTwoWheeler,
  "md:MdWbSunny": MdWbSunny,
  "md:MdNightlight": MdNightlight,
  "md:MdCloud": MdCloud,
  "md:MdAcUnit": MdAcUnit,
  "md:MdWhatshot": MdWhatshot,
  "md:MdWaterDrop": MdWaterDrop,
  "md:MdFlashOn": MdFlashOn,
  "md:MdDiamond": MdDiamond,
  "md:MdEmojiEvents": MdEmojiEvents,
  "md:MdSecurity": MdSecurity,
  "md:MdVpnKey": MdVpnKey,
  "md:MdLock": MdLock,
  "md:MdLockOpen": MdLockOpen,
  "md:MdMenuBook": MdMenuBook,
  "md:MdEmail": MdEmail,
  "md:MdPhone": MdPhone,
  "md:MdCalendarToday": MdCalendarToday,
  "md:MdSchedule": MdSchedule,
  "md:MdHourglassEmpty": MdHourglassEmpty,
  "md:MdAllInclusive": MdAllInclusive,
  "md:MdAdd": MdAdd,
  "md:MdRemove": MdRemove,
  "md:MdCheck": MdCheck,
  "md:MdClose": MdClose,
  "md:MdHelp": MdHelp,
  "md:MdPriorityHigh": MdPriorityHigh,
  "md:MdArrowUpward": MdArrowUpward,
  "md:MdArrowDownward": MdArrowDownward,
  "md:MdArrowBack": MdArrowBack,
  "md:MdArrowForward": MdArrowForward,
  "md:MdLocationOn": MdLocationOn,
  "md:MdPublic": MdPublic,
  "md:MdAnchor": MdAnchor,
  "md:MdExplore": MdExplore,
  "md:MdVisibility": MdVisibility,
  "md:MdPanTool": MdPanTool,
  "md:MdVolunteerActivism": MdVolunteerActivism,
  "md:MdHandshake": MdHandshake,
  "md:MdChat": MdChat,
  "md:MdCardGiftcard": MdCardGiftcard,
  "md:MdNotifications": MdNotifications,
  "md:MdFlag": MdFlag,
  "gi:GiFamilyHouse": GiFamilyHouse,
  "gi:GiLovers": GiLovers,
  "gi:GiBabyFace": GiBabyFace,
  "gi:GiCrossMark": GiCrossMark,
  "gi:GiDove": GiDove,
  "gi:GiOakLeaf": GiOakLeaf,
  "gi:GiPineTree": GiPineTree,
  "gi:GiSun": GiSun,
  "gi:GiMoon": GiMoon,
  "gi:GiFire": GiFire,
  "gi:GiWaterDrop": GiWaterDrop,
  "gi:GiLightningBow": GiLightningBow,
  "gi:GiDiamondRing": GiDiamondRing,
  "gi:GiCrown": GiCrown,
  "gi:GiShield": GiShield,
  "gi:GiKey": GiKey,
  "gi:GiPadlock": GiPadlock,
  "gi:GiBookCover": GiBookCover,
  "gi:GiGraduateCap": GiGraduateCap,
  "gi:GiBriefcase": GiBriefcase,
  "gi:GiAirplane": GiAirplane,
  "gi:GiSailboat": GiSailboat,
  "gi:GiCarKey": GiCarKey,
  "gi:GiCycle": GiCycle,
  "gi:GiPawPrint": GiPawPrint,
  "gi:GiCat": GiCat,
  "gi:GiSittingDog": GiSittingDog,
  "gi:GiHorseHead": GiHorseHead,
  "gi:GiDragonHead": GiDragonHead,
  "gi:GiGhost": GiGhost,
  "gi:GiSkullCrossedBones": GiSkullCrossedBones,
  "gi:GiMusicalNotes": GiMusicalNotes,
  "gi:GiPaintBrush": GiPaintBrush,
  "gi:GiPresent": GiPresent,
  "gi:GiWorld": GiWorld,
  "gi:GiAnchor": GiAnchor,
  "gi:GiCompass": GiCompass,
  "gi:GiHand": GiHand,
  "gi:GiPrayer": GiPrayer,
  "gi:GiTalk": GiTalk,
  "gi:GiEnvelope": GiEnvelope,
  "gi:GiPhone": GiPhone,
  "gi:GiCalendar": GiCalendar,
  "gi:GiSandsOfTime": GiSandsOfTime,
  "gi:GiInfinity": GiInfinity,
  "gi:GiCheckMark": GiCheckMark,
  "gi:GiCrossedSwords": GiCrossedSwords,
  "gi:GiArrowDunk": GiArrowDunk,
  "bs:BsHeart": BsHeart,
  "bs:BsStar": BsStar,
  "bs:BsHouse": BsHouse,
  "bs:BsPerson": BsPerson,
  "bs:BsPeople": BsPeople,
  "bs:BsEmojiSmile": BsEmojiSmile,
  "bs:BsSun": BsSun,
  "bs:BsMoon": BsMoon,
  "bs:BsCloud": BsCloud,
  "bs:BsSnow": BsSnow,
  "bs:BsFire": BsFire,
  "bs:BsDroplet": BsDroplet,
  "bs:BsLightning": BsLightning,
  "bs:BsGem": BsGem,
  "bs:BsAward": BsAward,
  "bs:BsShield": BsShield,
  "bs:BsKey": BsKey,
  "bs:BsLock": BsLock,
  "bs:BsUnlock": BsUnlock,
  "bs:BsBook": BsBook,
  "bs:BsMortarboard": BsMortarboard,
  "bs:BsBriefcase": BsBriefcase,
  "bs:BsAirplane": BsAirplane,
  "bs:BsWater": BsWater,
  "bs:BsCarFront": BsCarFront,
  "bs:BsBicycle": BsBicycle,
};

export const ICON_REGISTRY_KEYS = Object.keys(ICON_MAP);

export const EMOJI_CATEGORIES: { label: string; emojis: string[] }[] = [
  {
    label: "Smileys",
    emojis: ["😀", "😊", "😍", "🥰", "😎", "🤔", "😢", "😮", "🙂", "😇", "🤗", "😴"],
  },
  {
    label: "Hearts & symbols",
    emojis: ["❤️", "💛", "💚", "💙", "💜", "🖤", "💔", "💕", "✨", "⭐", "🌟", "💫"],
  },
  {
    label: "Family & people",
    emojis: ["👨", "👩", "👶", "👴", "👵", "👪", "💑", "💒", "🤵", "👰", "🧒", "👧"],
  },
  {
    label: "Nature",
    emojis: ["🌳", "🌸", "🍀", "🌻", "🌊", "🔥", "❄️", "☀️", "🌙", "⭐", "🌈", "🍃"],
  },
  {
    label: "Objects",
    emojis: ["💍", "🏠", "📖", "🎓", "💼", "✈️", "🚗", "🎵", "🎨", "📷", "🎁", "🔔"],
  },
  {
    label: "Animals",
    emojis: ["🐶", "🐱", "🐴", "🦁", "🐉", "🦋", "🐦", "🐢", "🐠", "🦊", "🐻", "🐼"],
  },
  {
    label: "Marks",
    emojis: ["✅", "❌", "❓", "❗", "➕", "➖", "⬆️", "⬇️", "⬅️", "➡️", "🔑", "🔒"],
  },
];

export function getConnectionIcon(key: string): IconComponent | null {
  return ICON_MAP[key] ?? null;
}

export function renderConnectionIcon(icon: ConnectionIconRef, size = 16): ReactNode {
  if (icon.kind === "emoji") {
    return (
      <span className="leading-none" style={{ fontSize: size }}>
        {icon.value}
      </span>
    );
  }
  const Comp = getConnectionIcon(icon.value);
  if (!Comp) return null;
  return <Comp size={size} className="text-dark-text" />;
}
